import fs from "node:fs";
import path from "node:path";
import {
  normalizeGameConfig,
  parseGameConfig,
  toGameSummary,
  type AnyGameConfig,
  type GameConfig,
  type GameSummary,
} from "./gameSchema.js";
import { runtimeConfig } from "./runtimeConfig.js";

const GAMES_ROOT = runtimeConfig.gamesRoot;
const warnedDirectories = new Set<string>();

function warnOnce(directory: string, message: string, error?: unknown): void {
  if (warnedDirectories.has(directory)) {
    return;
  }

  warnedDirectories.add(directory);
  console.warn(`[game-config] ${message}`);
  if (error) {
    console.warn(error);
  }
}

function getGameDirectories(): string[] {
  if (!fs.existsSync(GAMES_ROOT)) {
    return [];
  }

  return fs
    .readdirSync(GAMES_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

function sanitizeDirectoryName(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9-_]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

function findDirectoryByGameId(gameId: string): string | null {
  for (const directory of getGameDirectories()) {
    const config = loadConfigFromDirectory(directory);
    if (config?.gameId === gameId) {
      return directory;
    }
  }

  return null;
}

function loadConfigFromDirectory(directory: string): AnyGameConfig | null {
  const configPath = path.join(GAMES_ROOT, directory, "config.json");
  if (!fs.existsSync(configPath)) {
    warnOnce(directory, `Skipping '${directory}' because config.json is missing.`);
    return null;
  }

  try {
    const raw = JSON.parse(fs.readFileSync(configPath, "utf8"));
    return parseGameConfig(raw);
  } catch (error) {
    warnOnce(directory, `Skipping '${directory}' because its config could not be parsed.`, error);
    return null;
  }
}

export function loadAllGameConfigsRaw(): AnyGameConfig[] {
  return getGameDirectories()
    .map((directory) => loadConfigFromDirectory(directory))
    .filter((config): config is AnyGameConfig => config !== null)
    .sort((left, right) => left.title.localeCompare(right.title));
}

export function loadAllGameConfigs(): GameConfig[] {
  return loadAllGameConfigsRaw().map((config) => normalizeGameConfig(config));
}

export function loadGameConfigById(gameId: string): GameConfig | null {
  for (const directory of getGameDirectories()) {
    const config = loadConfigFromDirectory(directory);
    if (!config || config.gameId !== gameId) {
      continue;
    }

    return normalizeGameConfig(config);
  }

  return null;
}

export function loadRawGameConfigById(gameId: string): AnyGameConfig | null {
  for (const directory of getGameDirectories()) {
    const config = loadConfigFromDirectory(directory);
    if (config?.gameId === gameId) {
      return config;
    }
  }

  return null;
}

export function loadGameManifest(): GameSummary[] {
  return loadAllGameConfigs().map((config) => toGameSummary(config));
}

export function listGameConfigDirectories(): Array<{ gameId: string; directory: string }> {
  return getGameDirectories()
    .map((directory) => {
      const config = loadConfigFromDirectory(directory);
      if (!config) {
        return null;
      }

      return {
        gameId: config.gameId,
        directory,
      };
    })
    .filter((value): value is { gameId: string; directory: string } => value !== null);
}

export function createGameConfig(input: { config: unknown; directoryName?: string }): AnyGameConfig {
  const parsed = parseGameConfig(input.config);

  if (findDirectoryByGameId(parsed.gameId)) {
    throw new Error(`A game with id '${parsed.gameId}' already exists.`);
  }

  const preferredDirectory = sanitizeDirectoryName(input.directoryName ?? parsed.gameId);
  if (!preferredDirectory) {
    throw new Error("A valid directory name is required.");
  }

  const targetDirectory = path.join(GAMES_ROOT, preferredDirectory);
  if (fs.existsSync(targetDirectory)) {
    throw new Error(`Directory '${preferredDirectory}' already exists under Games.`);
  }

  fs.mkdirSync(targetDirectory, { recursive: true });
  fs.writeFileSync(path.join(targetDirectory, "config.json"), `${JSON.stringify(parsed, null, 2)}\n`, "utf8");

  const readmePath = path.join(targetDirectory, "README.md");
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(
      readmePath,
      `# ${parsed.title}\n\nGenerated by the TaPTaP admin dashboard.\n`,
      "utf8",
    );
  }

  return parsed;
}

export function updateGameConfig(gameId: string, config: unknown): AnyGameConfig {
  const directory = findDirectoryByGameId(gameId);
  if (!directory) {
    throw new Error(`No game exists for '${gameId}'.`);
  }

  const parsed = parseGameConfig(config);
  const duplicateDirectory = findDirectoryByGameId(parsed.gameId);
  if (parsed.gameId !== gameId && duplicateDirectory) {
    throw new Error(`A game with id '${parsed.gameId}' already exists.`);
  }

  const targetDirectory = path.join(GAMES_ROOT, directory);
  fs.writeFileSync(path.join(targetDirectory, "config.json"), `${JSON.stringify(parsed, null, 2)}\n`, "utf8");
  return parsed;
}

export function deleteGameConfig(gameId: string): { gameId: string; directory: string } {
  const directory = findDirectoryByGameId(gameId);
  if (!directory) {
    throw new Error(`No game exists for '${gameId}'.`);
  }

  fs.rmSync(path.join(GAMES_ROOT, directory), { recursive: true, force: false });
  return {
    gameId,
    directory,
  };
}
